#!/bin/bash

# these are declared in a specific order on purpose lol
FILE_PATH=$(dirname "$1")
FILE_NAME=$(basename "$1")
FILE_EXT="${FILE_NAME##*.}"
FILE_NAME="${FILE_NAME%.*}"

#echo "FILE_PATH: $FILE_PATH"
#echo "FILE_NAME: $FILE_NAME"
#echo "FILE_EXT: $FILE_EXT"

echo -n "Calling ffmpeg as: "
#echo "ffmpeg -i \"$1\" -c:v libaom-av1 -aom-params lossless=1 \"$FILE_PATH/$FILE_NAME.av1.$FILE_EXT\""
#ffmpeg -i "$1" -c:v av1_vaapi "$FILE_PATH/$FILE_NAME.av1.$FILE_EXT"
if [ $(ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 "$1") == "hevc" ]; then
	echo "Processing: \"$1\""
	ffmpeg -vaapi_device /dev/dri/renderD128 -i "$1" -vf 'format=nv12,hwupload' -c:v av1_vaapi -crf 24 -b:v 6000k "$FILE_PATH/$FILE_NAME.av1.$FILE_EXT" > /dev/null
else
	echo "Skipping: \"$1\""
fi
