#!/usr/bin/env bash

list() {
  ACCOUNT_ID="$1"
  API_TOKEN="$2"

 curl https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/tokens \
    -H "Authorization: Bearer $API_TOKEN" | jq
}

read() {
  ACCOUNT_ID="$1"
  API_TOKEN="$2" 
  TOKEN_ID="$3"
  curl https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/tokens/$TOKEN_ID \
    -H "Authorization: Bearer $API_TOKEN" | jq
}

"$@"
