{
 "title": "Hosts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Jafner-tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Boot Disk Used",
   "type": "graph",
   "description": "Percentage of boot disk used",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"jafner.tools\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"jafner.tools\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"})",
     "legendFormat": "Boot Disk Utilization"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Percentage of CPU utilized (averaged over last minute)",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode!=\"idle\",job=\"jafner.tools\"}[1m])) * 100",
     "legendFormat": "Utilization"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"jafner.tools\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"jafner.tools\"} * 100) / node_memory_MemTotal_bytes{job=\"jafner.tools\"})",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(node_network_receive_bytes_total{job=\"jafner.tools\"}[1m])*8)",
     "legendFormat": "Download"
    },
    {
     "expr": "sum by (job) (rate(node_network_transmit_bytes_total{job=\"jafner.tools\"}[1m])*8)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Swap Utilization",
   "type": "graph",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"jafner.tools\"} - node_memory_SwapFree_bytes{job=\"jafner.tools\"}) / (node_memory_SwapTotal_bytes{job=\"jafner.tools\"} )) * 100",
     "legendFormat": "Swap Utilization"
    }
   ]
  },
  {
   "title": "Boot Disk Total",
   "type": "stat",
   "description": "Total disk capacity",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"jafner.tools\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"jafner.tools\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"jafner.tools\"}"
    }
   ]
  },
  {
   "title": "Host Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"jafner.tools\"} - node_boot_time_seconds{job=\"jafner.tools\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"jafner.tools\"}"
    }
   ]
  },
  { "title": "Pihole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Boot Disk Used",
   "type": "graph",
   "description": "Percentage of boot disk used",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"pihole\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"pihole\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"})",
     "legendFormat": "Boot Disk Utilization"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Percentage of CPU utilized (averaged over last minute)",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode!=\"idle\",job=\"pihole\"}[1m])) * 100",
     "legendFormat": "Utilization"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"pihole\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"pihole\"} * 100) / node_memory_MemTotal_bytes{job=\"pihole\"})",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(node_network_receive_bytes_total{job=\"pihole\"}[1m])*8)",
     "legendFormat": "Download"
    },
    {
     "expr": "sum by (job) (rate(node_network_transmit_bytes_total{job=\"pihole\"}[1m])*8)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Swap Utilization",
   "type": "graph",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"pihole\"} - node_memory_SwapFree_bytes{job=\"pihole\"}) / (node_memory_SwapTotal_bytes{job=\"pihole\"} )) * 100",
     "legendFormat": "Swap Utilization"
    }
   ]
  },
  {
   "title": "Boot Disk Total",
   "type": "stat",
   "description": "Total disk capacity",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"pihole\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"pihole\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"pihole\"}"
    }
   ]
  },
  {
   "title": "Host Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"pihole\"} - node_boot_time_seconds{job=\"pihole\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"pihole\"}"
    }
   ]
  },
  { "title": "Router", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Boot Disk Used",
   "type": "graph",
   "description": "Percentage of boot disk used",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"router\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"router\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"})",
     "legendFormat": "Boot Disk Utilization"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Percentage of CPU utilized (averaged over last minute)",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode!=\"idle\",job=\"router\"}[1m])) * 100",
     "legendFormat": "Utilization"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"router\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"router\"} * 100) / node_memory_MemTotal_bytes{job=\"router\"})",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 31 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(node_network_receive_bytes_total{job=\"router\"}[1m])*8)",
     "legendFormat": "Download"
    },
    {
     "expr": "sum by (job) (rate(node_network_transmit_bytes_total{job=\"router\"}[1m])*8)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Swap Utilization",
   "type": "graph",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"router\"} - node_memory_SwapFree_bytes{job=\"router\"}) / (node_memory_SwapTotal_bytes{job=\"router\"} )) * 100",
     "legendFormat": "Swap Utilization"
    }
   ]
  },
  {
   "title": "Boot Disk Total",
   "type": "stat",
   "description": "Total disk capacity",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"router\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"router\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"router\"}"
    }
   ]
  },
  {
   "title": "Host Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"router\"} - node_boot_time_seconds{job=\"router\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"router\"}"
    }
   ]
  },
  { "title": "Joey-seedbox", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Boot Disk Used",
   "type": "graph",
   "description": "Percentage of boot disk used",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"joey-seedbox\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"joey-seedbox\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"})",
     "legendFormat": "Boot Disk Utilization"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Percentage of CPU utilized (averaged over last minute)",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode!=\"idle\",job=\"joey-seedbox\"}[1m])) * 100",
     "legendFormat": "Utilization"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"joey-seedbox\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"joey-seedbox\"} * 100) / node_memory_MemTotal_bytes{job=\"joey-seedbox\"})",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(node_network_receive_bytes_total{job=\"joey-seedbox\"}[1m])*8)",
     "legendFormat": "Download"
    },
    {
     "expr": "sum by (job) (rate(node_network_transmit_bytes_total{job=\"joey-seedbox\"}[1m])*8)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Swap Utilization",
   "type": "graph",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"joey-seedbox\"} - node_memory_SwapFree_bytes{job=\"joey-seedbox\"}) / (node_memory_SwapTotal_bytes{job=\"joey-seedbox\"} )) * 100",
     "legendFormat": "Swap Utilization"
    }
   ]
  },
  {
   "title": "Boot Disk Total",
   "type": "stat",
   "description": "Total disk capacity",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"joey-seedbox\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"joey-seedbox\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"joey-seedbox\"}"
    }
   ]
  },
  {
   "title": "Host Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"joey-seedbox\"} - node_boot_time_seconds{job=\"joey-seedbox\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"joey-seedbox\"}"
    }
   ]
  },
  { "title": "Joey-server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Boot Disk Used",
   "type": "graph",
   "description": "Percentage of boot disk used",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"joey-server\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"joey-server\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"})",
     "legendFormat": "Boot Disk Utilization"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Percentage of CPU utilized (averaged over last minute)",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode!=\"idle\",job=\"joey-server\"}[1m])) * 100",
     "legendFormat": "Utilization"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"joey-server\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"joey-server\"} * 100) / node_memory_MemTotal_bytes{job=\"joey-server\"})",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 61 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(node_network_receive_bytes_total{job=\"joey-server\"}[1m])*8)",
     "legendFormat": "Download"
    },
    {
     "expr": "sum by (job) (rate(node_network_transmit_bytes_total{job=\"joey-server\"}[1m])*8)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Swap Utilization",
   "type": "graph",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"joey-server\"} - node_memory_SwapFree_bytes{job=\"joey-server\"}) / (node_memory_SwapTotal_bytes{job=\"joey-server\"} )) * 100",
     "legendFormat": "Swap Utilization"
    }
   ]
  },
  {
   "title": "Boot Disk Total",
   "type": "stat",
   "description": "Total disk capacity",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"joey-server\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"joey-server\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"joey-server\"}"
    }
   ]
  },
  {
   "title": "Host Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"joey-server\"} - node_boot_time_seconds{job=\"joey-server\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"joey-server\"}"
    }
   ]
  }
 ]
}