{
 "title": "Smart Plugs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Usage (last month)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_power_kilowatts_total[30d])"
    }
   ]
  },
  {
   "title": "Total Usage (last week)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_power_kilowatts_total[7d])"
    }
   ]
  },
  {
   "title": "Total Usage (last 24h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_power_kilowatts_total[24h])"
    }
   ]
  },
  {
   "title": "Power Cost (last month)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_power_kilowatts_total[30d])*0.08192"
    }
   ]
  },
  {
   "title": "Power Cost (last week)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_power_kilowatts_total[7d])*0.08192"
    }
   ]
  },
  {
   "title": "Power Cost (last 24h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_power_kilowatts_total[24h])*0.08192"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "tasmota_energy_power_active_watts{}"
    }
   ]
  },
  {
   "title": "Power Rates",
   "type": "text",
   "gridPos": { "h": 11, "w": 3, "x": 17, "y": 10 },
   "options": {
    "content": "| Service | Charge |\n|:-------:|:------:|\n| Energy | $0.045351/kWh |\n| Distribution | $0.036569/kWh |\n| Total | $0.08192/kWh |"
   },
   "targets": [
    {
     "channel": "plugin/testdata/random-20Hz-stream",
     "filter": {
      "fields": [
       "Time",
       "Value"
      ]
     }
    }
   ]
  }
 ]
}