{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Percentage of CPU utilized (averaged over last minute)",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode!=\"idle\",job=\"$job\"}[1m])) * 100",
     "legendFormat": "Utilization"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"$job\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"$job\"} * 100) / node_memory_MemTotal_bytes{job=\"$job\"})",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(node_network_receive_bytes_total{job=\"$job\"}[1m])*8)",
     "legendFormat": "Download"
    },
    {
     "expr": "sum by (job) (rate(node_network_transmit_bytes_total{job=\"$job\"}[1m])*8)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Boot Disk Used",
   "type": "graph",
   "description": "Percentage of boot disk used",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"$job\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"$job\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"})",
     "legendFormat": "Boot Disk Utilization"
    }
   ]
  },
  {
   "title": "Swap Utilization",
   "type": "graph",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"$job\"} - node_memory_SwapFree_bytes{job=\"$job\"}) / (node_memory_SwapTotal_bytes{job=\"$job\"} )) * 100",
     "legendFormat": "Swap Utilization"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Host Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"$job\"} - node_boot_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Boot Disk Total",
   "type": "stat",
   "description": "Total disk capacity",
   "gridPos": { "h": 3, "w": 1, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"$job\",mountpoint=~\"/|/root.dev\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Minecraft Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (server_host) (minecraft_status_healthy{})",
     "legendFormat": "{{ server_host }}"
    }
   ]
  },
  {
   "title": "Minecraft Server Ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "minecraft_status_response_time_seconds{}",
     "legendFormat": "{{ server_host }}"
    }
   ]
  },
  {
   "title": "Minecraft Players Online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "minecraft_status_players_online_count{}",
     "legendFormat": "{{ server_host }}"
    }
   ]
  },
  {
   "title": "Traefik Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "sum by (service) (traefik_service_open_connections{})",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Traefik Requests in last minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "sum by (service) (rate(traefik_service_requests_total{}[1m]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "PiHole DNS Queries",
   "type": "piechart",
   "description": "Each point is a counter for the last 24 hours.",
   "gridPos": { "h": 8, "w": 3, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_queries_cached", "legendFormat": "Cached" },
    { "expr": "pihole_queries_forwarded", "legendFormat": "Forwarded" },
    { "expr": "pihole_ads_blocked_today", "legendFormat": "Blocked" }
   ]
  },
  {
   "title": "PiHole Unique Clients",
   "type": "stat",
   "gridPos": { "h": 8, "w": 1, "x": 23, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_unique_clients{}" }
   ]
  },
  {
   "title": "Deluge Torrents",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (tracker) (deluge_torrents{job=\"deluge\", tracker=~\"ggn|mam|emp|pub\"})",
     "legendFormat": "{{ tracker }}"
    }
   ]
  },
  {
   "title": "Deluge Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (tracker) (rate(deluge_libtorrent_net_recv_bytes_total{tracker=~\"ggn|mam|emp|pub\"}[24h]))",
     "legendFormat": "{{ tracker }} download"
    },
    {
     "expr": "sum by (tracker) (rate(deluge_libtorrent_net_sent_bytes_total{tracker=~\"ggn|mam|emp|pub\"}[24h]))",
     "legendFormat": "{{ tracker }} upload"
    }
   ]
  },
  {
   "title": "Deluge Torrent States",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "deluge_libtorrent_ses_num_seeding_torrents{}",
     "legendFormat": "{{tracker}} seeding"
    },
    {
     "expr": "deluge_libtorrent_ses_num_checking_torrents{} ",
     "legendFormat": "{{tracker}} checking"
    },
    {
     "expr": "deluge_libtorrent_ses_num_downloading_torrents{}",
     "legendFormat": "{{tracker}} downloading"
    },
    {
     "expr": "deluge_libtorrent_ses_num_error_torrents{}",
     "legendFormat": "{{tracker}} error"
    },
    {
     "expr": "deluge_libtorrent_ses_num_stopped_torrents{}",
     "legendFormat": "{{tracker}} stopped"
    }
   ]
  },
  {
   "title": "Uptime Kuma Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 4, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "sum by (monitor_name) (monitor_status{})",
     "legendFormat": "{{ monitor_name }}"
    }
   ]
  },
  {
   "title": "Uptime Kuma Time until Cert Expiry",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monitor_cert_days_remaining{}", "legendFormat": "{{ monitor_name }}" }
   ]
  },
  {
   "title": "Uptime Kuma Ping",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "monitor_response_time{}", "legendFormat": "{{ monitor_name }}" }
   ]
  },
  {
   "title": "Plex Library Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plex_library_section_size_count{name=\"Movies\"}",
     "legendFormat": "Movies"
    },
    {
     "expr": "plex_library_section_size_count{name=\"Shows\"}",
     "legendFormat": "TV Shows"
    },
    {
     "expr": "plex_library_section_size_count{name=\"Music\"}",
     "legendFormat": "Music Artists"
    }
   ]
  },
  {
   "title": "Plex Peak Sessions",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 4, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(plex_sessions_active_count[24h])",
     "legendFormat": "Last Day"
    },
    {
     "expr": "max_over_time(plex_sessions_active_count[7d])",
     "legendFormat": "Last Week"
    },
    {
     "expr": "max_over_time(plex_sessions_active_count[30d])",
     "legendFormat": "Last Month"
    }
   ]
  },
  {
   "title": "SabNZBD Download Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sabnzbd_queue_download_rate_bytes_per_second{}",
     "legendFormat": "Download Rate"
    }
   ]
  },
  {
   "title": "SabNZBD Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sabnzbd_queue_total_size_bytes{}",
     "legendFormat": "Queue Size"
    }
   ]
  },
  {
   "title": "SabNZBD Items in Queue",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 25 },
   "targets": [
    { "expr": "sabnzbd_queue_size{}", "legendFormat": "Items" }
   ]
  },
  {
   "title": "SabNZBD Total Download",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_download_bytes{}", "legendFormat": "{{ period }}" }
   ]
  },
  {
   "title": "Plex Active Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plex_sessions_active_count{}" }
   ]
  }
 ]
}