{
 "title": "Services",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Minecraft Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Minecraft Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (server_host) (minecraft_status_healthy{})",
     "legendFormat": "{{ server_host }}"
    }
   ]
  },
  {
   "title": "Server Ping",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "minecraft_status_response_time_seconds{}",
     "legendFormat": "{{ server_host }}"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "minecraft_status_players_online_count{}",
     "legendFormat": "{{ server_host }}"
    }
   ]
  },
  { "title": "Traefik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (service) (traefik_service_open_connections{})",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Requests in last minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (service) (rate(traefik_service_requests_total{}[1m]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  { "title": "Deluge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Torrents",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (tracker) (deluge_torrents{job=\"deluge\", tracker=~\"ggn|mam|emp|pub\"})",
     "legendFormat": "{{ tracker }}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (tracker) (rate(deluge_libtorrent_net_recv_bytes_total{tracker=~\"ggn|mam|emp|pub\"}[24h]))",
     "legendFormat": "{{ tracker }} download"
    },
    {
     "expr": "sum by (tracker) (rate(deluge_libtorrent_net_sent_bytes_total{tracker=~\"ggn|mam|emp|pub\"}[24h]))",
     "legendFormat": "{{ tracker }} upload"
    }
   ]
  },
  {
   "title": "Torrent States",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "expr": "deluge_libtorrent_ses_num_seeding_torrents{}",
     "legendFormat": "{{tracker}} seeding"
    },
    {
     "expr": "deluge_libtorrent_ses_num_checking_torrents{} ",
     "legendFormat": "{{tracker}} checking"
    },
    {
     "expr": "deluge_libtorrent_ses_num_downloading_torrents{}",
     "legendFormat": "{{tracker}} downloading"
    },
    {
     "expr": "deluge_libtorrent_ses_num_error_torrents{}",
     "legendFormat": "{{tracker}} error"
    },
    {
     "expr": "deluge_libtorrent_ses_num_stopped_torrents{}",
     "legendFormat": "{{tracker}} stopped"
    }
   ]
  },
  { "title": "Plex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Library Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plex_library_section_size_count{name=\"Movies\"}",
     "legendFormat": "Movies"
    },
    {
     "expr": "plex_library_section_size_count{name=\"Shows\"}",
     "legendFormat": "TV Shows"
    },
    {
     "expr": "plex_library_section_size_count{name=\"Music\"}",
     "legendFormat": "Music Artists"
    }
   ]
  },
  {
   "title": "Current Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plex_sessions_active_count{}" }
   ]
  },
  {
   "title": "Peak Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(plex_sessions_active_count[24h])",
     "legendFormat": "Last Day"
    },
    {
     "expr": "max_over_time(plex_sessions_active_count[7d])",
     "legendFormat": "Last Week"
    },
    {
     "expr": "max_over_time(plex_sessions_active_count[30d])",
     "legendFormat": "Last Month"
    }
   ]
  },
  { "title": "SabNZBD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Download Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sabnzbd_queue_download_rate_bytes_per_second{}"
    }
   ]
  },
  {
   "title": "Total Download",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_download_bytes{}", "legendFormat": "{{ period }}" }
   ]
  },
  {
   "title": "Items in Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    { "expr": "sabnzbd_queue_size{}" }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sabnzbd_queue_total_size_bytes{}"
    }
   ]
  },
  { "title": "Uptime-Kuma", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (monitor_name) (monitor_status{})",
     "legendFormat": "{{ monitor_name }}"
    }
   ]
  },
  {
   "title": "Time until Cert Expiry",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monitor_cert_days_remaining{}", "legendFormat": "{{ monitor_name }}" }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "monitor_response_time{}", "legendFormat": "{{ monitor_name }}" }
   ]
  },
  { "title": "PiHole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "DNS Queries",
   "type": "piechart",
   "description": "Each point is a counter for the last 24 hours.",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_queries_cached", "legendFormat": "Cached" },
    { "expr": "pihole_queries_forwarded", "legendFormat": "Forwarded" },
    { "expr": "pihole_ads_blocked_today", "legendFormat": "Blocked" }
   ]
  },
  {
   "title": "Unique Clients",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 3, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_unique_clients{}" }
   ]
  }
 ]
}